spring.application.name=edms
#spring.datasource.url= jdbc:sqlserver://10.1.0.89;encrypt=true;trustServerCertificate=true;databaseName=ramsdb
spring.datasource.url= jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=baylor
#spring.datasource.username=rams_user
spring.datasource.username=sa
#spring.datasource.password=9EB5503679B0eB2368AECDB2DA58880D2a?
spring.datasource.password=password=1
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.hbm2ddl.import_files=roles.sql
server.port=7000
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Set logging level for different packages
logging.level.org.springframework.web=DEBUG
logging.level.com.search=DEBUG
spring.jpa.open-in-view=true

# Set STMP Credentials
#spring.mail.host=mail.baylor-uganda.org
#spring.mail.port=25
#spring.mail.username=rams@baylor-uganda.org
spring.mail.host=smtp.mail.yahoo.com
spring.mail.port=465
spring.mail.username=bob.wabusa@coseke.com
spring.mail.password=kjgicnnwtijhklvl
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=false
